#if !canImport(ObjectiveC)
import XCTest

extension LockTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LockTests = [
        ("testOSUnfairLock", testOSUnfairLock),
        ("testPThreadMutex", testPThreadMutex),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LockTests.__allTests__LockTests),
    ]
}
#endif
